import { memo, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useCredentials } from '@/hooks/useCredentials';
import { useStudentProfile } from '@/hooks/useStudentProfile';
import { ChecklistItem, ChecklistItemStatus } from '@/components/checklist/ChecklistItem';
import { CircularProgress } from '@/components/dashboard/CircularProgress';
import { GenerateLinkDialog } from '@/components/share/GenerateLinkDialog';
import {
  ClipboardCheck,
  Download,
  Shield,
  CheckCircle2,
  AlertTriangle,
} from 'lucide-react';
import { Link } from 'react-router-dom';

interface ChecklistRequirement {
  id: string;
  title: string;
  description: string;
  check: () => ChecklistItemStatus;
}

const Checklist = memo(function Checklist() {
  const { clinicalReadiness, documents, requirements } = useCredentials();
  const { profile, getProfileCompleteness } = useStudentProfile();

  const checklistItems: ChecklistRequirement[] = useMemo(() => [
    {
      id: 'all-credentials',
      title: 'All Credentials Approved',
      description: 'All required credentials must be uploaded and approved',
      check: () => {
        if (clinicalReadiness.percentComplete === 100) return 'complete';
        if (clinicalReadiness.percentComplete >= 50) return 'warning';
        return 'incomplete';
      },
    },
    {
      id: 'no-expired',
      title: 'No Expired Documents',
      description: 'All documents must be current and valid',
      check: () => {
        const hasExpired = documents.some((doc) => doc.status === 'expired');
        return hasExpired ? 'warning' : 'complete';
      },
    },
    {
      id: 'profile-photo',
      title: 'Profile Photo Uploaded',
      description: 'A professional photo is required for your credential profile',
      check: () => (profile.profilePhotoUrl ? 'complete' : 'incomplete'),
    },
    {
      id: 'profile-complete',
      title: 'Profile Information Complete',
      description: 'Full name, contact info, and bio must be filled out',
      check: () => {
        const completeness = getProfileCompleteness();
        if (completeness === 100) return 'complete';
        if (completeness >= 60) return 'warning';
        return 'incomplete';
      },
    },
    {
      id: 'name-consistency',
      title: 'Name Matches All Documents',
      description: 'Your legal name must match across all uploaded credentials',
      check: () => {
        // For demo, we assume this is always complete if profile has a name
        return profile.firstName && profile.lastName ? 'complete' : 'incomplete';
      },
    },
    {
      id: 'work-history',
      title: 'Work History Added',
      description: 'At least one clinical experience or work history entry',
      check: () => (profile.workHistory.length > 0 ? 'complete' : 'incomplete'),
    },
  ], [clinicalReadiness, documents, profile, getProfileCompleteness]);

  const completedCount = checklistItems.filter(
    (item) => item.check() === 'complete'
  ).length;
  const overallPercentage = Math.round((completedCount / checklistItems.length) * 100);
  const isReady = completedCount === checklistItems.length;

  const handleDownloadReport = () => {
    // Create a simple compliance report
    const reportContent = `
CLINICAL COMPLIANCE REPORT
Generated: ${new Date().toLocaleDateString()}

Student: ${profile.firstName} ${profile.lastName}
Email: ${profile.email}

READINESS STATUS: ${isReady ? 'READY FOR CLINICAL ROTATION' : 'NOT READY'}
Overall Completion: ${overallPercentage}%

CHECKLIST ITEMS:
${checklistItems.map((item, index) => `
${index + 1}. ${item.title}
   Status: ${item.check().toUpperCase()}
   ${item.description}
`).join('')}

CREDENTIALS SUMMARY:
- Total Required: ${clinicalReadiness.totalRequired}
- Approved: ${clinicalReadiness.totalCompleted}
- Pending: ${clinicalReadiness.totalPending}
- Expiring Soon: ${clinicalReadiness.totalExpiring}

---
This report was generated by ClinCred Clinical Credentialing System.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <ClipboardCheck className="w-7 h-7" />
            Ready-for-Site Checklist
          </h1>
          <p className="text-muted-foreground">
            Complete all requirements before your clinical rotation
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleDownloadReport}>
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </Button>
          <GenerateLinkDialog />
        </div>
      </div>

      {/* Status Card */}
      <Card className={isReady ? 'border-success/50 bg-success/5' : ''}>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row items-center gap-6">
            <CircularProgress
              value={overallPercentage}
              size={140}
              label="Complete"
            />
            <div className="flex-1 text-center md:text-left">
              <div className="flex items-center justify-center md:justify-start gap-2 mb-2">
                {isReady ? (
                  <Badge variant="success" className="text-sm px-3 py-1">
                    <CheckCircle2 className="w-4 h-4 mr-1" />
                    Ready for Clinical Rotation
                  </Badge>
                ) : (
                  <Badge variant="warning" className="text-sm px-3 py-1">
                    <AlertTriangle className="w-4 h-4 mr-1" />
                    Action Required
                  </Badge>
                )}
              </div>
              <h2 className="text-xl font-semibold mb-1">
                {completedCount} of {checklistItems.length} Requirements Met
              </h2>
              <p className="text-muted-foreground">
                {isReady
                  ? 'Congratulations! You are ready to begin your clinical rotation.'
                  : 'Complete the remaining items to become clinical-ready.'}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Checklist Items */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="w-5 h-5" />
            Pre-Clinical Requirements
          </CardTitle>
          <CardDescription>
            Each item is automatically verified based on your credentials and profile
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {checklistItems.map((item) => (
            <ChecklistItem
              key={item.id}
              title={item.title}
              description={item.description}
              status={item.check()}
            />
          ))}
        </CardContent>
      </Card>

      {/* Quick Actions */}
      {!isReady && (
        <Card>
          <CardContent className="pt-6">
            <div className="flex flex-wrap gap-3">
              <Link to="/credentials">
                <Button variant="outline">Upload Missing Documents</Button>
              </Link>
              <Link to="/profile">
                <Button variant="outline">Complete Profile</Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
});

export default Checklist;
